export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  SIGNUP: '/signup',
  GOOGLE_CALLBACK: '/auth/google/callback',
  DASHBOARD: '/dashboard',
  PROPERTIES: '/properties',
  PROPERTY_DETAILS: '/properties/:id',
  ROOMS: '/rooms',
  TENANTS: '/tenants',
  TENANT_DETAILS: '/tenants/:id',
  PAYMENTS: '/payments',
  EXPENSES: '/expenses',
  COMPLAINTS: '/complaints',
  MAINTENANCE: '/maintenance',
  MESS: '/mess',
  VISITORS: '/visitors',
  STAFF: '/staff',
  REPORTS: '/reports',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  UNAUTHORIZED: '/unauthorized',
  NOT_FOUND: '*',
};
