version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: stayhub-dev-postgres
    restart: always
    environment:
      POSTGRES_DB: stayhub_db
      POSTGRES_USER: stayhub_admin
      POSTGRES_PASSWORD: stayhub_secret_pass
    ports:
      - "5432:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:7-alpine
    container_name: stayhub-dev-redis
    ports:
      - "6379:6379"

volumes:
  dev_postgres_data:
