name: Docker Build & Publish

on:
  push:
    branches: [main]

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Docker Image
        run: docker build -t stayhub-backend:latest ./backend

      - name: Build Gateway Docker Image
        run: docker build -t stayhub-gateway:latest ./gateway

      - name: Build Frontend Docker Image
        run: docker build -t stayhub-frontend:latest ./frontend
